# Author <edii87shadow@gmail.com> Novickyi Sergey

FROM centos:centos7
MAINTAINER The CentOS Project <cloud-ops@centos.org>

# generate locale and set timezone
RUN localedef --no-archive -i en_US -f UTF-8 en_US.UTF-8

# LABELS
LABEL Vendor="CentOS"

# ARGS
ARG PROJECT_NAME="Docker"
ARG php=56
ARG UID=0
ARG GID=0
ARG NODE=4.4.3

# PROJECT NAME
LABEL Project=$PROJECT_NAME

# INSTALL SUDO
RUN yum -y install sudo
RUN groupadd sudo ; useradd -g sudo sudo
RUN echo "sudo ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# CREATED USER
RUN echo $GID
RUN echo $UID
RUN echo $NODE

RUN groupadd -g $GID docker-data ; useradd -u $UID -g $UID -G sudo docker-data

RUN yum -y install wget; yum clean all
RUN yum -y update; yum clean all
RUN yum -y install epel-release; yum clean all
RUN yum -y install python-pip; yum clean all

#Install nodejs (link: https://hub.docker.com/_/node/ used docker hub node versions).
RUN set -ex \
  && for key in \
    9554F04D7259F04124DE6B476D5A82AC7E37093B \
    94AE36675C464D64BAFA68DD7434390BDBE9B9C5 \
    0034A06D9D9B0064CE8ADF6BF1747F4AD2306D93 \
    FD3A5288F042B6850C66B31F09FE44734EB7990E \
    71DCFD284A79C3B38668286BC97EC7A07EDE3FC1 \
    DD8F2338BAE7501E3DD5AC78C273792F7D83545D \
    B9AE9905FFD7803F25714661B63B535A4C206CA9 \
    C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8 \
  ; do \
    gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
  done

RUN curl -SLO "https://nodejs.org/dist/v$NODE/node-v$NODE-linux-x64.tar.xz" \
  && curl -SLO "https://nodejs.org/dist/v$NODE/SHASUMS256.txt.asc" \
  && gpg --batch --decrypt --output SHASUMS256.txt SHASUMS256.txt.asc \
  && grep " node-v$NODE-linux-x64.tar.xz\$" SHASUMS256.txt | sha256sum -c - \
  && tar -xJf "node-v$NODE-linux-x64.tar.xz" -C /usr/local --strip-components=1 \
  && rm "node-v$NODE-linux-x64.tar.xz" SHASUMS256.txt.asc SHASUMS256.txt

#Install NPM
RUN yum -y install npm

#Install CRONTAB
RUN yum -y install cronie

# RUNS add programs
RUN yum install -y vim

# Installing supervisor
RUN yum install -y python-setuptools
RUN easy_install pip
RUN pip install supervisor

#RUN supervisor
RUN /usr/bin/easy_install supervisor
RUN /usr/bin/easy_install supervisor-stdout

ADD . /src

USER docker-data

RUN cd /src; pip install -r requirements.txt

EXPOSE 8080

CMD ["python", "/src/index.py"]